; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27404.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__51CC5E43_common@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?common_function@@YAXXZ				; common_function
PUBLIC	__JustMyCode_Default
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?common_function@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+59
	DD	imagerel $unwind$?common_function@@YAXXZ
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?common_function@@YAXXZ DD 025051e01H
	DD	010a230fH
	DD	070030021H
	DD	05002H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\sindr\GitHub\TDT4102-HiR-CppGroundUp\Preprocessor\common.cpp
;	COMDAT ?common_function@@YAXXZ
_TEXT	SEGMENT
a$ = 4
?common_function@@YAXXZ PROC				; common_function, COMDAT

; 4    : {

$LN3:
	push	rbp
	push	rdi
	sub	rsp, 264				; 00000108H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 66					; 00000042H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	lea	rcx, OFFSET FLAT:__51CC5E43_common@cpp
	call	__CheckForDebuggerJustMyCode

; 5    : 	int a = 2; 

	mov	DWORD PTR a$[rbp], 2

; 6    : }

	lea	rsp, QWORD PTR [rbp+232]
	pop	rdi
	pop	rbp
	ret	0
?common_function@@YAXXZ ENDP				; common_function
_TEXT	ENDS
END
