; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27404.0 

	TITLE	C:\Users\sindr\GitHub\TDT4102-HiR-CppGroundUp\Preprocessor\common.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__51CC5E43_common@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?common_function@@YAXXZ				; common_function
PUBLIC	__JustMyCode_Default
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\sindr\GitHub\TDT4102-HiR-CppGroundUp\Preprocessor\common.cpp
;	COMDAT ?common_function@@YAXXZ
_TEXT	SEGMENT
_a$ = -8						; size = 4
?common_function@@YAXXZ PROC				; common_function, COMDAT

; 4    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __51CC5E43_common@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 5    : 	int a = 2; 

	mov	DWORD PTR _a$[ebp], 2

; 6    : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?common_function@@YAXXZ ENDP				; common_function
_TEXT	ENDS
END
